//countries list and emoji for users to add flags

const userCountryMap = {
    Tronamo: 'Australia',
    Brendan7625: 'Australia',
    lekh2003: 'Australia',
    Utochka: 'Belarus',
    larsvdb97: 'Belgium',
    luybo: 'Bulgaria',
    pfcballer: 'Canada',
    vcuber13: 'Canada',
    yoshinator879: 'Canada',
    Blueoanaoa: 'China',
    JZE: 'China',
    diudiuhamburger: 'China',
    gwj: 'China',
    XMeng: 'China',
    zyc: 'China',
    Ruan: 'China',
    yzx: 'China',
    chy: 'China',
    mochuannnn: 'China',
    Luisa15: 'Columbia',
    Lunarien: 'Czech Republic',
    asdfghqwerty: 'Finland',
    sq: 'France',
    Nikokas: 'France',
    Ladoly: 'France',
    Asbjorn: 'France',
    Netamma: 'France',
    daanbe: 'Germany',
    XLII: 'Germany',
    Dyslexus: 'Germany',
    RedstoneTim: 'Germany',
    Rouxles: 'Hong Kong',
    HackerTyper492: 'India',
    krjjod: 'India',
    imvelox: 'Italy',
    Nabbissimux: 'Italy',
    DedolCubing: 'Italy',
    thelegendary08: 'Malaysia',
    gottagitgud: 'Mexico',
    Rafael: 'Netherlands',
    JihadCubing: 'Netherlands',
    eff: 'Philippines',
    Dawidluna: 'Poland',
    kiraa96: 'Poland',
    pankubix: 'Poland',
    Verscup: 'Poland',
    Kingstone: 'Poland',
    Dekodzi: 'Poland',
    dphdmn: 'Russia',
    vovker: 'Russia',
    goodevening: 'Russia',
    quing: 'Russia',
    OsipovAleksander: 'Russia',
    GoldenBoy: 'Russia',
    IslamKitiev: 'Russia',
    Wrabbable: 'Russia',
    kv1nk: 'Russia',
    gontod195: 'Russia',
    YanikusGG: 'Russia',
    Antonyme: 'Russia',
    thetskerp: 'Russia',
    VyacheslavPervushin: 'Russia',
    vedroboev: 'Russia',
    dima: 'Russia',
    '1210': 'Russia',
    VanillaGawr: 'Russia',
    jug: 'Serbia',
    andrewtheslider: 'Serbia',
    peaceknight05: 'Singapore',
    SunOceanBeach: 'Taiwan',
    ben1996123: 'United Kingdom',
    Tree: 'United Kingdom',
    TDM: 'United Kingdom',
    Billabob: 'United Kingdom',
    sameer: 'United Kingdom',
    chbld: 'United Kingdom',
    JL586: 'United Kingdom',
    Garfologist: 'United Kingdom',
    darkanturian: 'United Kingdom',
    billzo: 'United Kingdom',
    Shadowslice: 'United Kingdom',
    Berkmann18: 'United Kingdom',
    sam596: 'United Kingdom',
    IgorTarasov: 'Ukraine',
    oliynykmax: 'Ukraine',
    faugore: 'Ukraine',
    Magentawolf27YT: 'United States of America',
    R14: 'United States of America',
    xsedim: 'United States of America',
    TheMatsValk: 'United States of America',
    tnum10: 'United States of America',
    SkyStep: 'United States of America',
    soup: 'United States of America',
    Scyter: 'United States of America',
    enigma515: 'United States of America',
    qqwref: 'United States of America',
    upvoid: 'United States of America',
    happydays: 'United States of America',
    LEBaldy: 'United States of America',
    strakerak: 'United States of America',
    c0wmanglr: 'United States of America',
    mAyo: 'United States of America',
    teri: 'United States of America',
    ShyGuy1265: 'United States of America',
    creepycat18: 'United States of America',
    Ianwubby: 'United States of America',
    BindeDSA: 'United States of America',
    Sethamajig: 'United States of America',
    MLGSheep1: 'United States of America',
    BrickInAPresent: 'United States of America',
    Owen: 'United States of America',
    Dapianokid: 'United States of America',
    Dreamer: 'United States of America',
    '105iqengineer': 'United States of America',
    Alex: 'United States of America',
    alka: 'United States of America',
    kleb: 'United States of America',
    HOGGYSIMP: 'United States of America',
    amazingpikachu37: 'United States of America',
    //14.01.2024
    XejuX: 'France',
};

const countryEmojis = {
    Australia: '🇦🇺',
    Belarus: '🇧🇾',
    Belgium: '🇧🇪',
    Bulgaria: '🇧🇬',
    Canada: '🇨🇦',
    China: '🇨🇳',
    Columbia: '🇨🇴',
    'Czech Republic': '🇨🇿',
    Finland: '🇫🇮',
    France: '🇫🇷',
    Germany: '🇩🇪',
    'Hong Kong': '🇭🇰',
    India: '🇮🇳',
    Italy: '🇮🇹',
    Malaysia: '🇲🇾',
    Mexico: '🇲🇽',
    Netherlands: '🇳🇱',
    Philippines: '🇵🇭',
    Poland: '🇵🇱',
    Russia: '🇷🇺',
    Serbia: '🇷🇸',
    Singapore: '🇸🇬',
    Taiwan: '🇹🇼',
    'United Kingdom': '🇬🇧',
    Ukraine: '🇺🇦',
    'United States of America': '🇺🇸',
};
